server:
 port: 8761
eureka:
  instance:
    hostname: 192.168.73.2
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

spring:
  application:
    name: BrdRegiterCenter